version: '2.4'

volumes:
  public:
    driver: local

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
  release:
    image: 600163339681.dkr.ecr.ap-southeast-2.amazonaws.com/docker-in-aws-fa/todobackend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings_release
      POSTGRES_HOST: db
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: password
  app:
    image: 600163339681.dkr.ecr.ap-southeast-2.amazonaws.com/docker-in-aws-fa/todobackend:${APP_VERSION}
    extends:
      service: release
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - public:/public
    healthcheck:
      test: curl -fs localhost:8000
      interval: 3s
      retries: 10
    ports:
      - 8000
    command:
      - uwsgi
      - --http=0.0.0.0:8000
      - --module=todobackend.wsgi
      - --master
      - --check-static=/public
      - --die-on-term
      - --processes=4
      - --threads=2
  acceptance:
    extends:
      service: release
    depends_on:
      app:
        condition: service_healthy
    environment:
      APP_URL: http://app:8000
    command:
      - bats
      - acceptance.bats
  migrate:
    extends:
      service: release
    depends_on:
      db:
        condition: service_healthy
    command:
      - python3
      - manage.py
      - migrate
      - --no-input
  db:
    image: postgres:11
    healthcheck:
      # test: mysqlshow -u $$MYSQL_USER -p$$MYSQL_PASSWORD
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 10
    environment:
      POSTGRES_DATABASE: todobackend
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: password
      POSTGRES_ROOT_PASSWORD: password